# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.76.153:3306/Ihf_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&nullCatalogMeansCurrent=true
    username: dba
    password: Ihf545586@

  cloud:
    nacos:
      discovery:
        server-addr: 121.5.76.153:8848
    sentinel:
      transport:
        dashboard: localhost:8858
  redis:
    host: 121.5.76.153
    port: 6379

# Stable Diffusion
stable-diffusion:
  address: "127.0.0.1"
  account: "IHUAFU"
  password: "Gongxifacai@2023"
