server:
  port: 8080
  max-http-header-size: 10240

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
    dynamic:
      lazy: true
      # 配置全局druid参数，请按需配置
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: demo
  profiles:
    active: @spring.active@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    serialization:
      indent_output: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        watch-delay: 1000


  # feign远程调用配置
feign:
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: x.trident.core.micro.core.feign.TridentFeignErrorDecoder
        requestInterceptors:
          - x.trident.core.micro.core.feign.TridentFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlConnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

# 资源扫描
scanner:
  open: false

# 日志记录
sys-log:
  # db-数据库，file-文件
  type: file
  file-save-path: _sys_logs

mybatis-plus:
  mapper-locations: classpath*:x/trident/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      table-underline: true

# actuator配置，给spring boot admin监控用
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
